version: '3'

services:
  mongo:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: items
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  machine-service:
    container_name: task_4
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports: 
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mongo